[package]
name = "rust_mir_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xlang_frontend.workspace = true
proc-macro2 = { version = "1.0.87", features = ["span-locations"] }


[lib]
proc-macro = true
