[package]
name = "abi-proc-macro"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
license = "BSD-2-Clause-Patent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
