[alias]
autobuild = ["run", "--package","autobuild","--release","--"]
configure = "autobuild configure"
build-lccc = "autobuild build"
clean-lccc = "autobuild clean"
run-lccc = "run --bin lccc -- --intree"
run-lccc-release = "run --release --bin lccc -- --intree"
guess = "autobuild guess"

[env]
AUTOBUILD_DIR={relative=true, value="autobuild"}

# [source.crates-io]
# replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
