
[targets.interning-static-syms]
src="interning-static-syms/src/lib.rs"
type="rust-procmacro"

[targets.rust-mir-macro]
deps=["xlang:xlang_frontend"]
src="rust_mir_macro/src/lib.rs"
type="rust-procmacro"

[targets.frontend-rust]
deps=["xlang:xlang", "interning-static-syms", "rust-mir-macro", "vendor:unicode-xid-0.2.2", "vendor:peekmore-1.3.0", "vendor:defile-0.2.0-rc1"]
src="src/lib.rs"
type="xlang:xlang-plugin"
