function(lccc_add_codegen backend)
    string(TOUPPER ${backend} BACKEND_NAME)
    set(BACKEND_DIR "LCCC_BACKEND_${BACKEND_NAME}_DIR")
    if(NOT DEFINED ${BACKEND_DIR})
        set(BACKEND_DIR "codegen-${backend}")
    else()
        set(BACKEND_DIR ${${BACKEND_DIR}})
    endif()
    add_subdirectory(${BACKEND_DIR})
    message(STATUS "Enabling Code generator: ${backend}")
endfunction()
function(lccc_add_language lang)
    string(TOUPPER ${lang} BACKEND_NAME)
    set(BACKEND_DIR "LCCC_BACKEND_${BACKEND_NAME}_DIR")
    if(NOT DEFINED ${BACKEND_DIR})
        set(BACKEND_DIR ${lang})
    else()
        set(BACKEND_DIR ${${BACKEND_DIR}})
    endif()
    add_subdirectory(${BACKEND_DIR})
    message(STATUS "Enabling Language: ${lang}")
endfunction()

function(lccc_link_backends lib)
    foreach(backend ${LCCC_ENABLE_BACKENDS})
        target_link_libraries(${lib} "codegen-${backend}-library${_LCCC_STAGE_SUFFIX}")
    endforeach()
endfunction()

function(lccc_depend_backends lib)
    foreach(backend ${LCCC_ENABLE_BACKENDS})
        add_dependencies(${lib} "codegen-${backend}-library${_LCCC_STAGE_SUFFIX}")
    endforeach()
endfunction()
