function(lccc_add_codegen backend)
    string(TOUPPER ${backend} BACKEND_NAME)
    set(BACKEND_DIR "LCCC_BACKEND_${BACKEND_NAME}_DIR")
    if(NOT DEFINED ${BACKEND_DIR})
        set(BACKEND_DIR "codegen-${backend}")
    else()
        set(BACKEND_DIR ${${BACKEND_DIR}})
    endif()
    add_subdirectory(${BACKEND_DIR})
endfunction()
function(lccc_add_language lang)
    string(TOUPPER ${lang} BACKEND_NAME)
    set(BACKEND_DIR "LCCC_BACKEND_${BACKEND_NAME}_DIR")
    if(NOT DEFINED ${BACKEND_DIR})
        set(BACKEND_DIR ${lang})
    else()
        set(BACKEND_DIR ${${BACKEND_DIR}})
    endif()
    add_subdirectory(${BACKEND_DIR})
endfunction()